# Generated by Django 3.0.2 on 2020-01-29 17:10

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(id=1, name='Administrators'),
        Group(id=2, name='Moderators'),
        Group(id=3, name='Users'),
        Group(id=4, name='Banned')
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
