# Generated by Django 3.0.2 on 2020-01-29 17:10

from django.db import migrations


def create_default_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.bulk_create([
        Role(id=1, name='Administrators'),
        Role(id=2, name='Moderators'),
        Role(id=3, name='Users'),
        Role(id=4, name='Banned')
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        #migrations.RunPython(create_default_roles),
    ]
