# Generated by Django 3.0 on 2019-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activatecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activatecode',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='activatecode',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
