# Generated by Django 3.0.2 on 2020-01-30 14:08

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200129_1710'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.models.AccountManager()),
            ],
        ),
    ]
