# Generated by Django 3.0.3 on 2020-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200130_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steam',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='avatarfull',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='avatarmedium',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='loccountrycode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profileurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
