# Generated by Django 3.0.3 on 2020-02-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('smadmins', '0004_remove_admin_server'),
        ('accounts', '0005_auto_20200214_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='display_role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AddField(
            model_name='account',
            name='display_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
