# Generated by Django 3.0.3 on 2020-02-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200214_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
    ]
