# Generated by Django 3.0.3 on 2020-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200214_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wtype',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Other')], default=1, null=True),
        ),
    ]
