# Generated by Django 3.0.3 on 2020-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200215_0708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentType',
            new_name='PaymentMethod',
        ),
    ]
