# Generated by Django 3.0.2 on 2020-01-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200102_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='type',
            new_name='wtype',
        ),
    ]
