# Generated by Django 3.0.3 on 2020-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200217_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tradeurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
