# Generated by Django 3.0.3 on 2020-02-19 21:13

from django.db import migrations

from djmoney.money import Money

def smsnumber_liveserver(apps, schema_editor):
    SMSNumber = apps.get_model('accounts', 'SMSNumber')

    SMSNumber.objects.bulk_create([
        SMSNumber(
            provider='liveserver',
            number=70068,
            expanse=Money(0.62, 'PLN'),
            money=Money(0.25, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=71068,
            expanse=Money(1.23, 'PLN'),
            money=Money(0.50, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=72068,
            expanse=Money(2.46, 'PLN'),
            money=Money(1.00, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=73068,
            expanse=Money(3.69, 'PLN'),
            money=Money(1.50, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=74068,
            expanse=Money(4.92, 'PLN'),
            money=Money(2.00, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=75068,
            expanse=Money(6.15, 'PLN'),
            money=Money(2.50, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=76068,
            expanse=Money(7.38, 'PLN'),
            money=Money(3.00, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=79068,
            expanse=Money(11.07, 'PLN'),
            money=Money(4.50, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=91058,
            expanse=Money(12.30, 'PLN'),
            money=Money(5.00, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=91758,
            expanse=Money(20.91, 'PLN'),
            money=Money(8.50, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=91958,
            expanse=Money(23.37, 'PLN'),
            money=Money(9.50, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=92058,
            expanse=Money(24.60, 'PLN'),
            money=Money(10.00, 'PLN')
        ),
        SMSNumber(
            provider='liveserver',
            number=92578,
            expanse=Money(30.75, 'PLN'),
            money=Money(12.50, 'PLN')
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_tradeurl'),
    ]

    operations = [
        migrations.RunPython(smsnumber_liveserver),
    ]
