# Generated by Django 3.0.3 on 2020-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200219_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscode',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
