# Generated by Django 3.0.3 on 2020-04-17 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('rules', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('register_data', models.DateTimeField(null=True)),
                ('members_must_register', models.BooleanField(default=False)),
                ('administrators', models.ManyToManyField(related_name='event_administrators', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='event_members', to=settings.AUTH_USER_MODEL)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_promoter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
