# Generated by Django 3.0.3 on 2020-04-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='register_data',
            new_name='register_date',
        ),
    ]
