# Generated by Django 3.0 on 2019-12-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191217_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='options',
            field=models.TextField(blank=True),
        ),
    ]
