# Generated by Django 3.0.2 on 2020-01-02 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_checkout_wallet_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Offer',
        ),
    ]
