# Generated by Django 3.0.1 on 2019-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ip', models.CharField(max_length=64, unique=True)),
                ('port', models.CharField(max_length=32)),
            ],
        ),
    ]
