# Generated by Django 3.0.1 on 2019-12-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20191230_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
