# Generated by Django 3.0.1 on 2019-12-30 13:21

from django.db import migrations


def create_default_games(apps, schema_editor):
    Game = apps.get_model('servers', 'Game')

    Game.objects.bulk_create([
        Game(tag="tf2", name="Team Fortess 2", app_id="440"),
        Game(tag="csgo", name="Counter Strike Global Offensive", app_id="730"),
        Game(tag="cs16", name="Counter Strike 1.6", app_id="10"),
        Game(tag="hurtworld", name="Hurtworld", app_id="393420")
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('servers', '0002_auto_20191230_1256'),
    ]

    operations = [
        migrations.RunPython(create_default_games)
    ]
