# Generated by Django 3.0.2 on 2020-01-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[(1, 'Podstawowy'), (2, 'Dodatkowy'), (3, 'Inny')], default=1, max_length=64, null=True),
        ),
    ]
