# Generated by Django 3.0 on 2019-12-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('premium', 'PREMIUM')], default='premium', max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='tag',
        ),
        migrations.AddField(
            model_name='bonus',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='options',
            field=models.TextField(default='{"account_id": 1}'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.BonusModule'),
        ),
    ]
