# Generated by Django 3.0.2 on 2020-01-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200102_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='secret',
        ),
    ]
