# Generated by Django 3.0 on 2019-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191217_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusmodule',
            name='tag',
            field=models.CharField(choices=[('premium_account', 'PREMIUM_ACCOUNT')], default='premium_account', max_length=32, unique=True),
        ),
    ]
