# Generated by Django 3.0.2 on 2020-02-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_offer_secret'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='bonus',
            old_name='module',
            new_name='type',
        ),
    ]
