# Generated by Django 3.0.3 on 2020-02-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='tag',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
