# Generated by Django 3.0.3 on 2020-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200304_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.AddField(
            model_name='group',
            name='tag',
            field=models.CharField(default='vip', max_length=32, unique=True),
        ),
    ]
