# Generated by Django 3.0.3 on 2020-03-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_auto_20200304_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('a', 'Admflag Reservation'), ('b', 'Admflag Generic'), ('c', 'Admflag Kick'), ('d', 'Admflag Ban'), ('e', 'Admflag Unban'), ('f', 'Admflag Slay'), ('g', 'Admflag Changemap'), ('h', 'Admflag Convars'), ('i', 'Admflag Config'), ('j', 'Admflag Chat'), ('k', 'Admflag Vote'), ('l', 'Admflag Password'), ('m', 'Admflag Rcon'), ('n', 'Admflag Cheats'), ('z', 'Admflag Root'), ('o', 'Admflag Custom1'), ('p', 'Admflag Custom2'), ('q', 'Admflag Custom3'), ('r', 'Admflag Custom4'), ('s', 'Admflag Custom5'), ('t', 'Admflag Custom6')], default='a', max_length=32)),
                ('end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
