# Generated by Django 3.0.2 on 2020-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200104_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postt',
            new_name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
