# Generated by Django 3.0.2 on 2020-01-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200105_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
