# Generated by Django 3.0.2 on 2020-01-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='categories',
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category'),
        ),
    ]
