# Generated by Django 3.0.2 on 2020-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smadmins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='immunity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
