# Generated by Django 3.0 on 2019-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_display_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
