# Generated by Django 3.0 on 2019-12-17 18:26

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191217_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
