# Generated by Django 3.0.2 on 2020-01-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200102_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bonus_max',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_percent',
            field=models.IntegerField(default=5),
        ),
    ]
