# Generated by Django 3.0.2 on 2020-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200102_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Other')], default=1, max_length=64, null=True),
        ),
    ]
