# Generated by Django 3.0.2 on 2020-01-05 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20200105_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
