# Generated by Django 3.0.3 on 2020-02-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200212_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Visible'), (0, 'Hidden')], default=1),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Opened'), (-1, 'Hidden')], default=1),
        ),
    ]
