# Generated by Django 3.0.3 on 2020-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionitem',
            name='image',
            field=models.ImageField(height_field=64, upload_to='reactions/', width_field=64),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
