# Generated by Django 3.0.3 on 2020-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20200328_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactionitem',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='reactionitem',
            name='image_url',
            field=models.URLField(default='localhost'),
        ),
    ]
