# Generated by Django 3.0.3 on 2020-03-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200328_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionitem',
            name='image_file',
            field=models.ImageField(upload_to='reactions/'),
        ),
    ]
