# Generated by Django 3.0.3 on 2020-03-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20200328_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactionitem',
            old_name='image_url',
            new_name='image',
        ),
    ]
