# Generated by Django 3.0.3 on 2020-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20200328_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoteanswer',
            name='bestanswer_ptr',
        ),
        migrations.AddField(
            model_name='post',
            name='best_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='promotion_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BestAnswer',
        ),
        migrations.DeleteModel(
            name='PromoteAnswer',
        ),
    ]
