# Generated by Django 3.0.3 on 2020-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20200328_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(related_name='_category_subcategories_+', to='forum.Category'),
        ),
    ]
