# Generated by Django 3.0.3 on 2020-04-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
    ]
