# Generated by Django 3.0.2 on 2020-01-22 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0004_auto_20191230_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
