# Generated by Django 3.0.2 on 2020-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smadmins', '0004_remove_admin_server'),
        ('servers', '0005_server_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(to='smadmins.Admin'),
        ),
    ]
