# Generated by Django 3.0.2 on 2020-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smadmins', '0002_auto_20200122_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='flags',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
