# Generated by Django 3.0.2 on 2020-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smadmins', '0003_auto_20200122_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='server',
        ),
    ]
